# Generated by Django 4.2.7 on 2023-11-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50)),
                ("subject", models.CharField(max_length=250)),
                ("desc", models.TextField()),
                ("date", models.DateField()),
            ],
        ),
    ]
