# Generated by Django 4.2.7 on 2023-11-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100)),
                ("date", models.DateField()),
            ],
        ),
    ]
